### ISSUE TITLE
Missing telegraf config?

### ISSUE THREAD

**Issue by ciuly** [chpro/fronius-grafana-dashboard#10]
Hello,

I am migrating your dashboard to latest grafana + flux (influxdb v2) + infinity plugin since the JSON one you are using is feature frozen and suggests moving to infinity.
It appears there is missing config in this repo, specifically for this line
https://github.com/chpro/fronius-grafana-dashboard/blob/51725ac419411105ed75a19e34895e296fdb1867/grafana/dashboard.json#L1641
Either that, or I missed some crucial step/understanding somewhere.

Could you check what is the source of that measurement? I was expecting to see it in telegraf.conf to be stored in influxdb.

Thank you

**Comment by chpro** [comment]
Hi,

thanks for the effort to update the dashboard. This query can be removed it seems to be a leftover from the project I have based this dashboard on.

**Comment by ciuly** [comment]
Sounds good, thank you
