### ISSUE TITLE
Influxdb key method obsolete

### ISSUE THREAD

**Issue by alejostenuki** [chpro/fronius-grafana-dashboard#3]
The Influxdb key method is obsolete.
Anyway, I had to update everything and something went wrong with my setup. I'm giving up. 
Consider uploading a Docker with everything loaded, too much trouble as it is. I spend an entire day and couldn't make it work.

**Comment by chpro** [comment]
I'm sorry to hear that you've had a difficult experience with the setup instruction. Your feedback is valuable to me, and I want to ensure that the experience is as smooth as possible. Additionally, I completely understand the frustration of spending a significant amount of time on troubleshooting.

I am not sure what you mean with `The Influxdb key method is obsolete.`. There is a token authentication used for telegram and Grafana which is described https://docs.influxdata.com/influxdb/v2/admin/tokens/ and https://docs.influxdata.com/influxdb/v2/api/#section/Authentication/TokenAuthentication and seem not to be obsolete.

If you can provide some more information I would be able to improve the instructions for the future.
