### ISSUE TITLE
Powerflow isnt working

### ISSUE THREAD

**Issue by Schmiddi1008** [chpro/fronius-grafana-dashboard#4]
Hi, 
ive configured the dashboard but the powerflow says "No Data". 

In the JSON API i have changed the Ip to the inverter. 

It Looks Like: 
192.168.2.106/status/powerflow 

If i put it in my browser, i can See the Output. 

Hope anyone can help me 
Thanks 

![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/d5be0872-31a2-44fc-a97d-639d9c60c574)

![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/0bcc523d-2574-43fa-84f4-4cf00bb83c78)

**Comment by chpro** [comment]
# Data source

The data source configuration seems to be okay. Can you check again by clicking on `Save and test` in your JSON datasource (Menu: `Connection` -> `Data Source`). You will get a success or error message displayed. 

**Success message:**
![Screenshot 2024-01-08 at 08 08 58](https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/c81d92c7-96d0-43a0-a73a-6c9ad9920204)

**Error message:**
![Screenshot 2024-01-08 at 08 09 15](https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/8f7f5cac-7243-4571-8b3c-674b584dd04c)

If your get **Success message** you are fine and can proceed to check the panel configuration

# Panel configuration

After wards please check the panel configuration. 
1. is the right Data Source selected
2. is the cache time for query `A` set to `0s`
![Screenshot 2024-01-08 at 08 18 27](https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/88b55eb4-c24e-4d73-a0d6-4abf15dd578b)

## Query inspector
Open the `Query inspector` and click on `Refresh` you should get an JSON response like

```
{
  "request": {
    "url": "api/datasources/proxy/uid/c22db054-79a4-46c1-a749-9a7556a2a4b1",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "common": {
      "datestamp": "08.01.2024",
      "timestamp": "07:20:39"
    },
    "inverters": [
      {
        "BatMode": 5,
        "CID": 0,
        "DT": 0,
        "E_Total": 6283611.136388889,
        "ID": 1,
        "P": 39.07825469970703,
        "SOC": 6.2
      }
    ],
    "site": {
      "BackupMode": false,
      "BatteryStandby": false,
      "E_Day": null,
      "E_Total": 6283611.136388889,
      "E_Year": null,
      "MLoc": 0,
      "Mode": "bidirectional",
      "P_Akku": -1.0588949918746948,
      "P_Grid": 2531.4,
      "P_Load": -2570.374594116211,
      "P_PV": 66.49000930786133,
      "rel_Autonomy": 1.5163001612849285,
      "rel_SelfConsumption": 100
    },
    "version": "12"
  }
}
```
The important part is within the `response` node this should match the configuration of query `A`. If you miss some of the attributes or they are named differently try to remove/adapt the field from configuration.

> *HINT*: Also the status panel for battery and grid is using the same data source
> ![Screenshot 2024-01-08 at 08 26 35](https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/75ecae88-160f-4adb-ab13-542a3487c0f8)

**Comment by Schmiddi1008** [comment]
Thank you for your help. It works :) 

Dont know why, but the whole query fields wasnt there. 

![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/8b5f7b49-423c-432e-9477-d5e357db4a8a)

Now i want to change the Update Intervall in query options like yours. I cant Chance them to 500ms 

![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/c289091a-0a18-416c-8b1d-f122b903cb17)

An the last is Pvforecast. It says also "no data". 
Ive put the link with all the data in the Telegraf.conf , but the data source found 0 measurements 

![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/79859930-7633-41e5-9372-c47cc23865e6)

The link Looks like: 

Https://api.forecast.solar/estimate/watthours/day/xx/xx/20/-10/11.48?time=utc 

![image](https://github.com/chpro/fronius-grafana-dashboard/assets/155877587/903c6771-5dc5-4fb7-8909-cbeb5a72add2)

**Comment by chpro** [comment]
# For the power flow panel

The refresh time can not be configured on the panel it self but only on the dashboard. Then all panels on the dashboard are refreshed within same time interval. 

![Screenshot 2024-01-08 at 14 28 33](https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/eda952a0-2cb2-46e1-833f-747ff00aa3af)

Please change also the cache time to 0s first, then on every refresh new data is loaded.

![294859497-c289091a-0a18-416c-8b1d-f122b903cb17](https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/67aa7fd2-9a29-4f85-a9fb-beb50766336e)

# For the forecast api

Can you please open another issue. hen it is easier to track for me and keep the discussion ongoing.

It may take several hours before first data is recorded. Can you can check Influx data explorer (runs on port 8086) if there is any data available. The data should look like
![Screenshot 2024-01-08 at 14 42 30](https://github.com/chpro/fronius-grafana-dashboard/assets/5706722/3ae6e8cd-dc80-498b-af37-198c1976c1b9)
only one data point per day. If nothing is there please also post the telegraf config.
